# Generated by Django 3.1.5 on 2021-09-24 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
